In [3]:
import numpy as np
import matplotlib.pyplot as plt

import torch
from torch.nn import Module, Sequential, Linear, Conv2d, ReLU, Tanh, Dropout, BatchNorm1d
from torch.utils.data import DataLoader
from torch import optim
from torch.nn.functional import normalize

In [28]:
a = torch.tensor([[1,1,1], [-2,1,-2]]).float()
print(a)
print(a.abs().max(1, keepdim=True)[0])
b = a/ a.abs().max(1, keepdim=True)[0]
print(b)
print(a)

tensor([[ 1.,  1.,  1.],
        [-2.,  1., -2.]])
tensor([[1.],
        [2.]])
tensor([[ 1.0000,  1.0000,  1.0000],
        [-1.0000,  0.5000, -1.0000]])
tensor([[ 1.,  1.,  1.],
        [-2.,  1., -2.]])
