In [ ]:
import tensorflow as tf
tf.__version__
tf.config.list_physical_devices('GPU')

In [3]:
import numpy as np
import matplotlib.pyplot as plt

import torch
from torch.nn import Module, Sequential, Linear, Conv2d, ReLU, Tanh, Dropout, BatchNorm1d
from torch.utils.data import DataLoader
from torch import optim
from torch.nn.functional import normalize

In [ ]:
from ignite.engine import Engine
def eval_step(engine, batch):
    return batch

default_evaluator = Engine(eval_step)

metric = FID(num_features=32*32)
metric.attach(default_evaluator, "fid")
y_true = train_dataset_target[:10].detach().clone().cpu()
y_pred = img[-1]
state = default_evaluator.run([[y_pred, y_true]])
print(state.metrics["fid"])
print(train_dataset_target.shape)

In [28]:
a = torch.tensor([[1,1,1], [-2,1,-2]]).float()
print(a)
print(a.abs().max(1, keepdim=True)[0])
b = a/ a.abs().max(1, keepdim=True)[0]
print(b)
print(a)

tensor([[ 1.,  1.,  1.],
        [-2.,  1., -2.]])
tensor([[1.],
        [2.]])
tensor([[ 1.0000,  1.0000,  1.0000],
        [-1.0000,  0.5000, -1.0000]])
tensor([[ 1.,  1.,  1.],
        [-2.,  1., -2.]])


In [1]:
import ipynbname
currentNotebook = ipynbname.name()
print(currentNotebook)

playground-jvsc-0570be55-e890-43f5-9fb1-6ed2e4d1ae3f9dce2f81-42c1-4b17-94e9-4cc53a575d50
